name: Publish package to the Maven Central Repository and GitHub Packages

on:
  push:
    tags:
      - 'release/*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Parse version
        id: release_version
        uses: ashley-taylor/regex-property-action@v1.3
        with:
          value: "${{ github.ref_name }}"
          regex: "release/"
          replacement: ""
      - uses: actions/checkout@v4
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
      - name: Publish to the Maven Central Repository
        run: mvn -P deploy --batch-mode clean deploy -DskipTests -Drevision=${{ steps.release_version.outputs.value }}
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
          MAVEN_GPG_KEY: ${{ secrets.GPG_SIGNING_KEY }}
